name: food_market_app
description: A Flutter food market app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-111.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  retrofit: ^4.0.1
  equatable: ^2.0.5
  dio: ^5.2.0+1
  json_annotation: ^4.8.1
  meta: ^1.9.1
  get_it: ^7.6.0
  gap: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  retrofit_generator: ^7.0.1
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/Schyler-Medium.otf
          weight: 500